### ISSUE TITLE
[Bug] Cancel build on "get sources" step

### ISSUE THREAD

**Issue by Smert** [node-ci/nci#38]
One day the build process hung in step "get sources" on command "git fetch". But I could not cancel it:

```
Fri, 07 Sep 2018 10:27:27 GMT] [resources error handler] Error is occurred during requesting /builds cancel: Error: Can`t cancel build: no current cmd
    at Group.self.canceled (/home/dmitry/WebstormProjects/nci-app/node_modules/nci/lib/executor/base.js:279:11)
    at Group.<anonymous> (/home/dmitry/WebstormProjects/nci-app/node_modules/twostep/lib/twoStep.js:171:15)
    at next (/home/dmitry/WebstormProjects/nci-app/node_modules/twostep/lib/twoStep.js:159:9)
    at iterateSteps (/home/dmitry/WebstormProjects/nci-app/node_modules/twostep/lib/twoStep.js:164:7)
    at /home/dmitry/WebstormProjects/nci-app/node_modules/twostep/lib/twoStep.js:129:3
    at /home/dmitry/WebstormProjects/nci-app/node_modules/twostep/lib/twoStep.js:187:32
    at Executor.cancel (/home/dmitry/WebstormProjects/nci-app/node_modules/nci/lib/executor/base.js:275:2)
    at Group.<anonymous> (/home/dmitry/WebstormProjects/nci-app/node_modules/nci/lib/distributor.js:504:14)
    at Group.<anonymous> (/home/dmitry/WebstormProjects/nci-app/node_modules/twostep/lib/twoStep.js:171:15)
    at next (/home/dmitry/WebstormProjects/nci-app/node_modules/twostep/lib/twoStep.js:159:9)

```

NCI cancel method works with `self.currentCmd` which declared only in project configuration steps

**Comment by okv** [comment]
Hello.
Yes, this is known issue.
I'll try to investigate that to give you more details.
